### PR TITLE
Add Using section to Readme

### PR DESCRIPTION
**Pull request by tibbon**

### CODE REVIEW

**Comment by jaredpetersen** [comment]
Thanks for your pull request, @tibbon!

However, I don't think that this change is necessary. It's a React project and has a `package.json` that lists each of the different commands that can be run.

Anyone trying to contribute to the codebase should already know React and would therefore already know that they need Node.js and npm installed. They should also already know how to install the dependencies and run the application because the commands for that are standard and are mentioned in the `package.json`.

I'm going to close this pull request, but don't hesitate to contribute in the future. It's recommended that you open an issue first before putting any work in though so that the community can validate the change before anyone puts time into it.

**Comment by jaredpetersen** [comment]
As far as using the software goes, the application is live on http://jaredpetersen.github.io/codeprinter/, which is linked in the description.

The documentation could probably be beefed up though. I went over it again after reading your message and realized there's not much there beyond screenshots.

**Comment by tibbon** [comment]
Ah! I didn't realize it was live when I came across the readme, and was trying to run it locally :)

Given that my boss dislikes me cutting/pasting our code into external environments, running it locally is also probably ideal.

**Comment by jaredpetersen** [comment]
@tibbon I added a usage section to the repository. Your suggested version didn't have correct information and the dependencies were **very** out of date anyways so a lot more than a documentation update was in order. JavaScript moves pretty fast. I mentioned your username in one of the commit messages, so you're forever immortalized there 🗿 

Thank you for your suggestion and deeper explanation.

**Pull request closed without merging**
